version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  fitnesse:
    build:
      context: fitnesse/
      args:
        FITNESSE_VERSION: $FITNESSE_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /Users/christophwolff/src/wlm/test/src/main/resources/:/work/root
    ports:
      - "8888:8888"
    networks:
      - elk
  mongo:
    image: mongo
    ports:
      - 27017:27017
  app:
    build:
      context: ../app/
    ports:
      - "8080:8080"
    networks:
      - elk
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      MONGODB_HOST: mongo

networks:

  elk:
    driver: bridge
